pages:
  stage: deploy
  tags:
    - alpine
  script:
    - echo 'Just declare artifact...'
  artifacts:
    paths:
    - src/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push"