

docker build:
  stage: build
  tags:
    - npm
  script:
    - cd backend
    - npm install
    - NODE_ENV=test_docker_free npm run test
 # rules:
 #   - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"
 #   - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "22-implement-pipeline"
#

#pages:
#  stage: deploy
#  tags:
#    - alpine
#  script:
#    - echo 'Just declare artifact...'
#  artifacts:
#    paths:
#    - src/public
#  rules:
#    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
#