stages:
  - build-backend
  - build-frontend
  - build-docker
  - deploy


build-backend:
  stage: build-backend
  tags:
    - npm
  before_script:
    - cd backend
  script:
    - npm install

build-frontend:
  stage: build-frontend
  tags:
    - npm
  before_script:
    - cd frontend
  script:
    - npm install

build-docker:
  stage: build-docker
  tags:
    - docker
  script:
    - NODE_ENV=test npm run test
  rules:
    - when: never

 # rules:
 #   - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"
 #   - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "22-implement-pipeline"
#

pages:
  image: ubuntu:22.04
  stage: deploy
  script:
    - apt get nodejs npm
    - cd frontend
    - npm install
    - npm run build
    - cd ..
    - cd backend
    - NODE_ENV=docker_prod npm run test
  artifacts:
    paths:
    - src/public

