docker build:
  stage: build
  script: NODE_ENV=docker_dev docker-compose up --build --detach
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"



pages:
  stage: deploy
  tags:
    - alpine
  script:
    - echo 'Just declare artifact...'
  artifacts:
    paths:
    - src/public
  only:
    refs:
      - dev
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
