docker build:
  stage: build
  script: NODE_ENV=test npm run tes
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"



pages:
  stage: deploy
  tags:
    - alpine
  script:
    - echo 'Just declare artifact...'
  artifacts:
    paths:
    - src/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH