version: '3.0'
services:
  mongo:
    image: mongo
    container_name: cargonaut_mongo
    ports:
      - "8080:8080"
  node:
    build: .
    container_name: cargonaut
    ports:
      - "8008:8008"
    depends_on:
      - mongo
    environment:
      - "NODE_ENV=${NODE_ENV}"
