###
POST http://localhost:8008/req/create
Content-Type: application/json
sessionid: 1111
cuid: system

{
"date": "1-12-2022",
"user": "620cbeaecc90432d95b598a0",
"cargo": "I have only a sports bag with me."
}

###

###
POST http://localhost:8008/req/update
Content-Type: application/json
sessionid: 1111
cuid: system

{
"date": "1-12-2022",
"user": "620cbeaecc90432d95b598a0",
"cargo": "I have only a sports bag with me."
"requestStatus": "accepted"
"trackingStatus": "pending"
}

###
GET http://localhost:8008/req/getAll
sessionid: 1111
cuid: system

###

GET http://localhost:8008/req/findById/620cbeaecc90432d95b598a0
sessionid: 1111
cuid: system

###

DELETE http://localhost:8080/req/delete/620cbeaecc90432d95b598a6
Content-Type: application/json
sessionid: 1111
cuid: system
