###
POST http://localhost:8008/ride/create
Content-Type: application/json
sessionid: 1111
cuid: system

{
"date": "1-12-2022",
"origin": "munich",
"destination": "berlin",
"user": "620cbeaecc90432d95b598a",
"pendingReqs" : [],
"accReqs": []
}

###
POST http://localhost:8008/ride/update
Content-Type: application/json
sessionid: 1111
cuid: system

{
"date": "1-12-2022",
"origin": "munich",
"destination": "berlin",
"user": "620cbeaecc90432d95b598a",
"pendingReqs" : ["620cbeaecc90432d95b598a0"],
"accReqs": []
}

###

GET http://localhost:8008/ride/getAll
sessionid: 1111
cuid: system

###

GET http://localhost:8008/ride/findById/620cbeaecc90432d95b598a0
sessionid: 1111
cuid: system

###

DELETE http://localhost:8080/ride/delete/620cbeaecc90432d95b598a6
Content-Type: application/json
sessionid: 1111
cuid: system
