###
POST http://localhost:8008/user/create
Content-Type: application/json
sessionid: 1111
cuid: system

{
"name": "test1",
"birthdate": "1-1-2000",
"email": "muster@gmail.de",
"password": "willBeHashedAndSaltedInTheFuture",
"vehicles": []
}

###

POST http://localhost:8008/user/update/62b1b922d87d2267525e9e69
Content-Type: application/json
sessionid: 1111
cuid: system

{
"name": "test1",
"birthdate": "1-1-2000",
"email": "muster@gmail.de",
"password": "willBeHashedAndSaltedInTheFuture",
"vehicles": ["620cbeaecc90432d95b598a0"],
"averageEvalOfRides": 4
}

###

GET http://localhost:8008/user/getAll
sessionid: 1111
cuid: system

###

GET http://localhost:8008/user/findById/62b4622328ed0b0006bdba40
sessionid: 1111
cuid: system

###

DELETE http://localhost:8008/user/delete/620cbeaecc90432d95b598a6
Content-Type: application/json
sessionid: 1111
cuid: system
