###
POST http://localhost:8008/vehicle/create
Content-Type: application/json
sessionid: 1111
cuid: system

{
  "type": "standard car",
  "numberOfSeats": 4,
  "notes": "looks ugly, but moves"
}

###

GET http://localhost:8008/vehicle/getAll
sessionid: 1111
cuid: system

###

GET http://localhost:8008/vehicle/findById/62b0af7cac53f8f52347a7f2
sessionid: 1111
cuid: system

###

DELETE http://localhost:8008/vehicle/delete/62b0af7cac53f8f52347a7f2
Content-Type: application/json
sessionid: 1111
cuid: system